### ISSUE TITLE
login message

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#16]
<img width="1210" alt="Screenshot 2021-03-25 at 17 45 40" src="https://user-images.githubusercontent.com/4582388/112510720-fe3b3700-8d91-11eb-93ba-ad61fedab6d5.png">

- please spell `beamOS` with lowercase b
- please replace `Mr Beam GmbH` by `Mr Beam Lasers GmbH`
- please fix serial number (currently it's just `2T`)
- please consider that the device might have more than one local IP (Wifi and ethernet or ethernet an AP). Rename to `Local IPs` and list all (external) local IPs

nice ascii art btw ;-)

**Comment by amrsoll** [comment]
Yeah, but I'm too lazy to make the thing with the local IPs, and it would clutter the greeting message.
The other stuff is fixed :) (in a future image build)
