### ISSUE TITLE
OctoPrint version is incorrect

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#21]
OctioPrint version is systemwide 'mrbeam2-stable' 

<img width="263" alt="Screenshot 2021-04-01 at 15 48 06" src="https://user-images.githubusercontent.com/4582388/113303729-ab1d3300-9301-11eb-8f0a-10b12e1a787e.png">

**Comment by amrsoll** [comment]
Yes I am currently working on the software update part. Right now it shows the branch it has been installed with instead of the version.
