### ISSUE TITLE
OctoPrint wants an Update

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#23]
<img width="325" alt="Screenshot 2021-04-01 at 16 10 19" src="https://user-images.githubusercontent.com/4582388/113307413-61364c00-9305-11eb-8ea0-e900d6f7a2d7.png">

**Comment by amrsoll** [comment]
Yep, had to remove the code that was overriding the settings in `config.yaml`

**Comment by amrsoll** [comment]
Because of how the `sotwareupdate` plugin protects the update mechanism for OctoPrint, I've had to hard code it into `config.yaml`, remove the `octoprint` update mechanism from the MrBeamPlugin `octoprint_mrbeam/softwareupdate.py` and set a fake `displayVersion` key tag for now.
