### ISSUE TITLE
Merge new image branches [3]

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#28]
https://github.com/mrbeam/BeamOS/blob/mrbeam/TODO.md

https://github.com/mrbeam/OctoPrint-FindMyMrBeam/pull/27
https://github.com/mrbeam/MrBeamLedStrips/pull/22
https://github.com/mrbeam/BeamOS/issues/29
https://github.com/mrbeam/MrBeamPlugin/pull/1218

> OctoPrint diffs (no beta branch)

https://github.com/mrbeam/OctoPrint/commits/mrbeam-buster

**Comment by amrsoll** [comment]
The OctoPrint changes :
- `piptestballoon/setup.py` changes have been tested in the oprint venv
- `pip.py` is Less restrictive than before (does not block sudo installs)

These changes are required for OctoPrint to be able to update the packages that are installed in a root-level venv.

IObeam 
- Only changes to location of stuff

FindMyMrBeam
- 

Netconnectd
- Changes from Manuel Mclure
- Could still require the use of the hostname for the default AP name

Warning: mrbeam/MrBeamPlugin#1227 is still open

**Comment by amrsoll** [comment]
- Branch naming convention: `mrbeam2-<stable/beta/dev>-<debian version>`
- Hardcode the branches and the pip locations in `softwareupdate.py`
- Do NOT include the changes to `softwareupdate.py` for now 
  > use `config.yaml` to set the `branch` and `pip_command` when needed for the new image

## For the Beta release

In case these changes do not work for the Beta release

1. Create a release candidate from the commit preceding these merge commits (required on all repos which are buggy)
2. Possibility to add fixes in the RC branches
3. Merge the RC to the beta branch AND the develop branch.

**Comment by andywerner** [comment]
Todos:
- MrBPlugin: 
  - separate softwareupdate.py in separate PR
  - https://github.com/mrbeam/MrBeamPlugin/pull/1218
  - https://github.com/mrbeam/MrBeamPlugin/pull/1221
- Test OctoPrint changes on old image and read OP update documentation
- iobeam changes

**Comment by amrsoll** [comment]
Update :
Because 

- The iobeam socket change is not relevant to the new image
- The changes in the softwareupdate part of the MrBeamPlugin will be merged tomorrow, still a separate branch for the new image.

This has been postponed.
The mrbeam/MrBeamLedStrips#22 Pr has been merged.

**Comment by JFSolution** [comment]
@amrsoll whats the current status here? can it be closed?
