### ISSUE TITLE
Netconectd: Change indication of wifi signal strength [1]

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#47]

**Comment by khaledsherkawi** [comment]
Hey @Gallore , 
Please check the following:
Current settings:
quality >= 60 --> 4 green bars
quality >= 40 --> 3 yellow bars
quality >= 20 --> 2 red bars
else --> 1 red bar (quality between 0 and 19)
 
![1](https://user-images.githubusercontent.com/54568489/116877315-136f7500-ac1e-11eb-978c-56fd5001285f.png)
![2](https://user-images.githubusercontent.com/54568489/116877321-14080b80-ac1e-11eb-99d0-bbdf7d54bc11.png)
![3](https://user-images.githubusercontent.com/54568489/116877323-14a0a200-ac1e-11eb-9c5a-05e6efbb7de8.png)

**Comment by andywerner** [comment]
@khaledsherkawi Can you please remove the colors. The goal is to make users less worried/irritated if the reception is mediocre. Especially the yellow color does not help towards this goal,
