### ISSUE TITLE
Netconnectd: buttons in advanced settings should give better feedback [2]

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#48]

**Comment by amrsoll** [comment]
Description: The start / stop AP buttons do not seem to work

**Comment by khaledsherkawi** [comment]
Hey @Gallore ,

@amrsoll is right about this. The start/stop functionality seems to be faulty.
Shall we remove this button or work on it?? especially that the other button is fine and we can reset daemon

**Comment by amrsoll** [comment]
I think we just remove it. We don't allow the change to be permanent anyway...

**Comment by andywerner** [comment]
I'd like to understand WHY this AP button doe not work. I s this a bug we weed to report to Manuel?
I'd like to keep the AP button in the UI though. But priorities are discussable. ;-)

**Comment by khaledsherkawi** [comment]
A new issue is added to the server repo: 

https://github.com/mrbeam/netconnectd_mrbeam/issues/8
