### ISSUE TITLE
Edit bash history, aliases and data visualised

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#5]
fine tune the new image 

bash history:
- `i2cdetect -y 1`
- `vcgencmd measure_temp`
- 'iobeamcli'
- 'iobeamcli -c fan off'
- 'iobeamcli -c fan on 100'
- i2cset -y 1 0x2a 0x81 0x64               //Exhaust 100%
- i2cset -y 1 0x2a 0x81 0x00               //Exhaust off
- i2cset -y 1 0x2c 0x82 0x64              	//Compressor 200 mbar
- i2cset -y 1 0x2c 0x82 0x00		//Compressor off
- i2cset -y 1 0x2c 0x87 0x64		//Ozon		100 PPM
- i2cset -y 1 0x2c 0x87 0x00                //Ozon off
- `sudo reboot now`

aliases:
- alias ..="cd .."
- alias ...="cd ../.."
- alias ll="ls -l"
- alias l="ls -al"

data  on login screen
- serial number
- image version
- plugin version
- current OP state (idle, slicing, printing - I know, probably hard to get this information…)
- iobeam details (lid open/closd, i2c devices, …)

**Comment by amrsoll** [comment]
Aliases already included :heavy_check_mark:

**Comment by amrsoll** [comment]
I'm also going to set new aliases
```
i2cdetect='i2cdetect -y 1'
i2cset='i2cset -y 1'
```

**Comment by amrsoll** [comment]
Fixed in ae4bee54

**Comment by andywerner** [comment]
> I'm also going to set new aliases
> 
> ```
> i2cdetect='i2cdetect -y 1'
> i2cset='i2cset -y 1'
> ```

uff... really??? it hides the original tool ...
What about
mrb_i2cdetect='i2cdetect -y 1'
mrb_i2cset='i2cset -y 1'

**Comment by amrsoll** [comment]
I've changed it so that, even if you do add the extra `-y 1`, it won't interfere

**Comment by amrsoll** [comment]
and no it doesn't hide the tool, you can definitely still call it with the full path. There is no plan on using an other i2c bus, so that is the choice I made. No need to create extra mrb_something functions
