### ISSUE TITLE
Unify commit hashes in repositories [1]

### ISSUE THREAD

**Issue by khaledsherkawi** [mrbeam/BeamOS#58]
In the following repositiories, beta and stable branches have different commit hashes although they have same code

MrBeamDoc
mrb_hw_info
iobeam

**Comment by amrsoll** [comment]
Purpose: When switching Stable-Beta, those packages are unnecessaritly updated

**Comment by khaledsherkawi** [comment]
https://bitbucket.org/mrbeam/mrb_hw_info/pull-requests/6/merge-mrbeam2-stable-into-mrbeam2-beta
https://bitbucket.org/mrbeam/iobeam/pull-requests/70/merge-mrbeam2-stable-into-mrbeam2-beta

**Comment by khaledsherkawi** [comment]
MrBeamDoc will be resolved in the next Beta release
