### ISSUE TITLE
OP does not automatically connect to GRBL

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#7]
OP does not automatically connect to GRBL

**Comment by amrsoll** [comment]
Yeah it is strange, because the config.yaml explicitely says that it should ...

**Comment by andywerner** [comment]
something is also strange about the config.yaml... needs more investigation.

**Comment by amrsoll** [comment]
I think it's an issue with OctoPrint though, see mrbeam/MrBeamPlugin#1215
