### ISSUE TITLE
/etc/mrbeam [2]

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#8]
1. needs to be created automatically (including model, serial, hostname)
2. use nicer image fingerprint (eg: "PROD-2021-03-19")
3. make /etc/mrbeam writeable for everyone. (my point is convenience from the terminal and some user space processes are going to write there as well in the future.)
4. Is it "the only source of truth" and all other file follow the values in here? (hostname?)

**Comment by amrsoll** [comment]
1. Well, that is the point of mrb_check, no? To set the device serial? Or should that logic also change with the updates to mrb_check?
2. yep
3. but then why have it the /etc folder if we don't want to protect it? Isn't the point of /etc/mrbeam to be set in stone?
4. For the hostname, I have now changed the plugin behaviour so that it ignores the hostname field if it's empty
  For the rest, I would say yes? The date of creation, of assembly, series and model shouldn't change outside of upgrades.

**Comment by andywerner** [comment]
1. Not exactly. Some parts were not mrb_check like serial or host name. However, the "previous" way is not clean or anything... Would be good to have all these values set by one tool. Could be mrb_check, but doesn't have to. 

Let's discuss 3 and 4 in person.

**Comment by andywerner** [comment]
Axel and I just agreed on this:
- /etc/mrbeam will remain the only source and he place to edit the values that are in there.
- hostname: there will be a script/service that sets the hostname to what is configured in /etc/mrbeam during shutdown. According functionality in our plugin will be removed. old images get the same script/service per our plugin migrations.
- Serial and hostname: there will be two scripts to calculate and set serial and hostname from raspi serial number (or any given value.) these will be run on first boot.
- We will have two variants of our image: 
  - a configured variant for production (e.g."2S" variant) which will have a fully configured /etc/mrbeam file after the first boot.
  - a "generic" one intended for our workshop which does not make assumptions about model, name etc... these values need to be configured manually or  by a backup-restore script.

**Comment by amrsoll** [comment]
From phone conv:
- Create variants that preset most values in /etc/mrbeam
- The base `mrbeam` variant doesn't prepopulate /etc/mrbeam values

For production: Use a `mrbeam-2X` variant
For repairs : Use `mrbeam` base variant
For dev device: `mrbeam-dev` variant

**Comment by amrsoll** [comment]
See #10 , The serial number should auto apply on first boot now.
