### ISSUE TITLE
Create symlinks for site-packages and dist-packages in HOME

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#9]

**Comment by andywerner** [comment]
Maybe the terms site-packages and dist-packages are outdated...
But convenience links from home dir for the packages we usually work on would be helpful.

**Comment by amrsoll** [comment]
I chose to have dev version images that have the source code easily accessible from the home dir, therefore I think we shouldn't be using symlinks to some site-packages in a specific environment...

**Comment by andywerner** [comment]
ok.
